name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Release
        uses: ./workflows/actions/incremental-release
        with:
          DEFAULT_INCREMENT: minor
          GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
