name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
      - name: Release
        uses: ./.github/actions/incremental-release
        with:
          DRY_RUN: false
          DEFAULT_INCREMENT: patch
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
